### ISSUE TITLE
multiple definition of `yylloc'

### ISSUE THREAD

**Issue by wizhippo** [bigtreetech/CB1-Kernel#1]
Building on WSL2 with Ubuntu 22.04

First try ./build.sh config got error: build/mkcmd.sh: line 244: python: command not found

sudo apt install python2

Then edited build/mkcmd.sh and changed python to python2

./build.sh config then worked

./build.sh failed missing directory brandy/brandy-2.0/spl

symlinked brandy/brandy-2.0/spl-pub to brandy/brandy-2.0/spl

Now I get the error
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here

Found solution in https://github.com/BPI-SINOVOIP/BPI-M4-bsp/issues/4 and added extern to the mentioned file and change another reference from python to python2

Build success.

When I get the board I will give the build a go.

thank you for releasing this.

Is this at some point going to match the release found at https://github.com/bigtreetech/CB1/releases

**Comment by wizhippo** [comment]
Using the new branch and it works thank you.

**Comment by nachannon** [comment]
Thank you very much had the same issues compiled fine now
